"""Add location and industry fields to Company

Revision ID: 1bdb4fd961ce
Revises: 05d0d69f8f5e
Create Date: 2025-01-27 18:05:34.320175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdb4fd961ce'
down_revision = '05d0d69f8f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=False))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('posted_date')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('industry')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
